create table if not exists system_secret (
 secret_key varchar(255) primary key,
 encrypted_value clob not null,
 encryption_version integer not null,
 updated_at timestamp not null,
 updated_by varchar(255)
);
create table if not exists trusted_certificate (
 id bigint generated by default as identity primary key,
 certificate_alias varchar(255) not null,
 subject_dn varchar(2000) not null,
 issuer_dn varchar(2000) not null,
 serial_number varchar(255) not null,
 sha256_fingerprint varchar(128) not null unique,
 valid_from timestamp not null,
 valid_until timestamp not null,
 source_host varchar(512),
 source_port integer,
 status varchar(64) not null,
 certificate_der blob not null,
 created_at timestamp not null,
 created_by varchar(255)
);
