-- Security and authorization schema for H2.
-- UTF-8: H2 stores character data as Unicode. Keep Flyway encoding=UTF-8.

create table if not exists app_user (
    id bigint generated by default as identity primary key,
    username varchar(255) not null,
    password_hash varchar(255) not null,
    display_name varchar(255),
    email varchar(255),
    enabled boolean not null default true,
    password_change_required boolean not null default false,
    created_at timestamp not null default current_timestamp,
    created_by varchar(255),
    updated_at timestamp,
    updated_by varchar(255),
    constraint uk_app_user_username unique (username)
);

create table if not exists app_role (
    id bigint generated by default as identity primary key,
    role_code varchar(100) not null,
    role_name varchar(255) not null,
    constraint uk_app_role_code unique (role_code)
);

create table if not exists app_user_role (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_app_user_role_user foreign key (user_id) references app_user(id),
    constraint fk_app_user_role_role foreign key (role_id) references app_role(id)
);

create index if not exists idx_app_user_enabled on app_user(enabled);
create index if not exists idx_app_user_role_role on app_user_role(role_id);
