create table xml_file_revision (
    id bigint generated by default as identity primary key,
    xml_file_id bigint not null,
    revision_no integer not null,
    save_type varchar(50) not null,
    target_file_path varchar(2000),
    backup_file_path varchar(2000),
    diff_summary varchar(2000),
    change_count integer not null default 0,
    xsd_validation_requested boolean not null default false,
    xsd_validation_status varchar(50),
    user_note varchar(1000),
    created_at timestamp not null,
    created_by varchar(255),
    constraint fk_xml_file_revision_file foreign key (xml_file_id) references xml_file(id)
);
create table xml_file_diff_entry (
    id bigint generated by default as identity primary key,
    revision_id bigint not null,
    xml_file_id bigint not null,
    change_type varchar(50) not null,
    xml_path varchar(2000),
    old_value clob,
    new_value clob,
    display_label varchar(1000),
    constraint fk_xml_file_diff_revision foreign key (revision_id) references xml_file_revision(id),
    constraint fk_xml_file_diff_file foreign key (xml_file_id) references xml_file(id)
);
create index idx_xml_file_revision_file on xml_file_revision(xml_file_id);
create index idx_xml_file_diff_revision on xml_file_diff_entry(revision_id);
create index idx_xml_file_diff_file on xml_file_diff_entry(xml_file_id);
