ALTER TABLE app_user ADD COLUMN authentication_source VARCHAR(32) DEFAULT 'LOCAL' NOT NULL;
ALTER TABLE app_user ADD COLUMN failed_login_attempts INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE app_user ADD COLUMN locked_until TIMESTAMP NULL;

CREATE TABLE app_user_password_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_app_user_password_history_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
CREATE INDEX idx_app_user_password_history_user ON app_user_password_history(user_id, created_at);
