app.name=M2M XML EDITOR
main.jar=app.jar
main.class=org.springframework.boot.loader.launch.JarLauncher
java.options=-Dfile.encoding=UTF-8
# Desktop integracio kapcsolok. Pelda: -Dnav.xsdparsertool.desktop.enabled=false
# A teljes kikapcsolashoz a java.options sorhoz adhato: -Dnav.xsdparsertool.desktop.enabled=false

