create table xml_file_lock_release_request (
    id number(19,0) generated by default as identity primary key,
    xml_file_id number(19,0) not null,
    requester_username varchar2(255 char) not null,
    requester_browser_session_id varchar2(100 char),
    owner_username varchar2(255 char) not null,
    owner_browser_session_id varchar2(100 char),
    status varchar2(50 char) not null,
    message varchar2(1000 char),
    response_message varchar2(1000 char),
    requested_at timestamp not null,
    responded_at timestamp,
    closed_by varchar2(255 char),
    force_closed_at timestamp,
    constraint fk_lock_release_request_xml_file foreign key (xml_file_id) references xml_file(id)
);

create index idx_lock_release_owner_status on xml_file_lock_release_request(owner_username, owner_browser_session_id, status);
create index idx_lock_release_requester on xml_file_lock_release_request(requester_username, requester_browser_session_id);
