-- NAV M2M Bizonylat online validation and calculation latest-state fields.
alter table m2m_submission add (nav_validacio_ugy_azonosito varchar2(100 char));
alter table m2m_submission add (nav_validacio_statusz varchar2(50 char));
alter table m2m_submission add (nav_validacio_result_code varchar2(100 char));
alter table m2m_submission add (nav_validacio_result_message clob);
alter table m2m_submission add (nav_validacio_hibak clob);
alter table m2m_submission add (nav_validacios_tanusitvany clob);
alter table m2m_submission add (nav_validacio_response_body clob);
alter table m2m_submission add (nav_validacio_started_at timestamp);
alter table m2m_submission add (nav_validacio_finished_at timestamp);
alter table m2m_submission add (nav_validacio_last_checked_at timestamp);
alter table m2m_submission add (nav_validacio_message_id varchar2(100 char));
alter table m2m_submission add (nav_validacio_correlation_id varchar2(100 char));
alter table m2m_submission add (nav_kalkulacio_ugy_azonosito varchar2(100 char));
alter table m2m_submission add (nav_kalkulacio_statusz varchar2(50 char));
alter table m2m_submission add (nav_kalkulacio_result_code varchar2(100 char));
alter table m2m_submission add (nav_kalkulacio_result_message clob);
alter table m2m_submission add (nav_kalkulacio_hiba_kod varchar2(200 char));
alter table m2m_submission add (nav_kalkulacio_hiba_uzenet clob);
alter table m2m_submission add (nav_kalkulacio_mezo_azonosito varchar2(255 char));
alter table m2m_submission add (nav_kalkulacio_szabaly_azonosito varchar2(255 char));
alter table m2m_submission add (nav_kalkulacio_tomorites varchar2(20 char));
alter table m2m_submission add (nav_kalkulalt_xml clob);
alter table m2m_submission add (nav_kalkulacio_response_body clob);
alter table m2m_submission add (nav_kalkulacio_started_at timestamp);
alter table m2m_submission add (nav_kalkulacio_finished_at timestamp);
alter table m2m_submission add (nav_kalkulacio_last_checked_at timestamp);
alter table m2m_submission add (nav_kalkulacio_message_id varchar2(100 char));
alter table m2m_submission add (nav_kalkulacio_correlation_id varchar2(100 char));
