create table github_template_repository (
    repository_name varchar2(255 char) primary key,
    description_text varchar2(2000 char),
    repository_updated_at timestamp,
    repository_url varchar2(1000 char),
    archived_flag number(1) default 0 not null,
    last_synced_at timestamp not null
);
create table github_template_release (
    id number(19) generated by default as identity primary key,
    repository_name varchar2(255 char) not null,
    release_tag varchar2(255 char) not null,
    last_synced_at timestamp not null,
    constraint uk_github_template_release_rt unique (repository_name, release_tag),
    constraint fk_github_template_release_repo foreign key (repository_name) references github_template_repository(repository_name) on delete cascade
);
create index idx_github_template_release_repo on github_template_release(repository_name);
create table github_template_sync_state (
    id number(19) primary key,
    organization_name varchar2(255 char) not null,
    last_checked_at timestamp,
    last_successful_sync_at timestamp,
    repository_count number(10) not null
);
