-- NAV XSD Parser Tool initial database schema for Oracle 19c+.
-- Database character set should be AL32UTF8.

create table xml_file (
    id number(19) generated by default as identity primary key,
    file_name varchar2(500 char) not null,
    original_file_name varchar2(500 char),
    file_path varchar2(2000 char) not null,
    file_size_bytes number(19) default 0 not null,
    form_type varchar2(100 char),
    form_version varchar2(100 char),
    root_element varchar2(255 char),
    namespace_uri varchar2(1000 char),
    user_note varchar2(1000 char),
    source_type varchar2(50 char) default 'UNKNOWN' not null,
    status varchar2(50 char) default 'REGISTERED' not null,
    large_file_mode number(1) default 0 not null,
    archived number(1) default 0 not null,
    archived_at timestamp,
    archived_by varchar2(255 char),
    created_at timestamp default current_timestamp not null,
    created_by varchar2(255 char),
    updated_at timestamp,
    updated_by varchar2(255 char),
    constraint uk_xml_file_file_name unique (file_name)
);

create index idx_xml_file_created_at on xml_file(created_at);
create index idx_xml_file_status on xml_file(status);
create index idx_xml_file_form on xml_file(form_type, form_version);

create table xml_file_session (
    id number(19) generated by default as identity primary key,
    xml_file_id number(19) not null,
    session_id varchar2(100 char) not null,
    active number(1) default 1 not null,
    created_at timestamp default current_timestamp not null,
    created_by varchar2(255 char),
    closed_at timestamp,
    closed_by varchar2(255 char),
    constraint uk_xml_file_session_session_id unique (session_id),
    constraint fk_xml_file_session_file foreign key (xml_file_id) references xml_file(id)
);

create index idx_xml_file_session_file on xml_file_session(xml_file_id);
create index idx_xml_file_session_active on xml_file_session(active);

create table processing_job (
    id number(19) generated by default as identity primary key,
    job_id varchar2(100 char) not null,
    xml_file_id number(19),
    job_type varchar2(100 char) not null,
    status varchar2(50 char) not null,
    progress_percent number(10),
    progress_message varchar2(2000 char),
    started_at timestamp,
    finished_at timestamp,
    requested_cancel_at timestamp,
    error_message clob,
    created_at timestamp default current_timestamp not null,
    created_by varchar2(255 char),
    updated_at timestamp,
    updated_by varchar2(255 char),
    constraint uk_processing_job_job_id unique (job_id),
    constraint fk_processing_job_file foreign key (xml_file_id) references xml_file(id)
);

create index idx_processing_job_status on processing_job(status);
create index idx_processing_job_file on processing_job(xml_file_id);

create table operation_audit_log (
    id number(19) generated by default as identity primary key,
    operation_type varchar2(100 char) not null,
    xml_file_id number(19),
    job_id varchar2(100 char),
    revision_id number(19),
    username varchar2(255 char),
    result varchar2(50 char),
    message varchar2(2000 char),
    details_json clob,
    created_at timestamp default current_timestamp not null,
    constraint fk_audit_log_file foreign key (xml_file_id) references xml_file(id)
);

create index idx_audit_log_created_at on operation_audit_log(created_at);
create index idx_audit_log_xml_file on operation_audit_log(xml_file_id);
create index idx_audit_log_operation on operation_audit_log(operation_type);

create table xpath_validation_request (
    id varchar2(36 char) not null primary key,
    request_id varchar2(18 char) not null unique,
    request_timestamp_utc timestamp not null,
    form_name varchar2(20 char) not null,
    form_version varchar2(10 char) not null,
    validator_status varchar2(10 char) not null,
    result_status varchar2(10 char),
    create_result_mode varchar2(10 char) not null,
    session_id varchar2(64 char) not null,
    result clob,
    result_file_path varchar2(1024 char),
    error_count number(10),
    technical_error_message clob,
    created_at timestamp not null,
    created_by varchar2(64 char),
    updated_at timestamp not null,
    updated_by varchar2(64 char)
);

create index idx_xpath_validation_request_created_at on xpath_validation_request(created_at);

create table xpath_validation_error (
    id varchar2(36 char) not null primary key,
    request_entity_id varchar2(36 char) not null,
    request_id varchar2(18 char) not null,
    error_code varchar2(64 char),
    error_message clob,
    severity varchar2(32 char),
    dynamic_page_index varchar2(64 char),
    element_id varchar2(255 char),
    rule_id varchar2(64 char),
    path clob,
    created_at timestamp not null,
    created_by varchar2(64 char)
);

create index idx_xpath_validation_error_request_entity_id on xpath_validation_error(request_entity_id);

create table xpath_validation_request_journal (
    id varchar2(36 char) not null primary key,
    request_entity_id varchar2(36 char) not null,
    request_id varchar2(18 char) not null,
    event_timestamp_utc timestamp not null,
    old_validator_status varchar2(10 char),
    new_validator_status varchar2(10 char),
    old_result_status varchar2(10 char),
    new_result_status varchar2(10 char),
    message clob,
    session_id varchar2(64 char),
    created_at timestamp not null,
    created_by varchar2(64 char)
);

create index idx_xpath_validation_request_journal_request_entity_id on xpath_validation_request_journal(request_entity_id);
