ALTER TABLE app_user ADD authentication_source VARCHAR2(32) DEFAULT 'LOCAL' NOT NULL;
ALTER TABLE app_user ADD failed_login_attempts INTEGER DEFAULT 0 NOT NULL;
ALTER TABLE app_user ADD locked_until TIMESTAMP NULL;

CREATE TABLE app_user_password_history (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_app_user_password_history_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE
);
CREATE INDEX idx_app_user_password_history_user ON app_user_password_history(user_id, created_at);
