CREATE TABLE system_secret (
 secret_key VARCHAR2(255 CHAR) NOT NULL,
 encrypted_value CLOB NOT NULL,
 encryption_version NUMBER(10) NOT NULL,
 updated_at TIMESTAMP NOT NULL,
 updated_by VARCHAR2(255 CHAR),
 CONSTRAINT pk_system_secret PRIMARY KEY (secret_key)
);

CREATE TABLE trusted_certificate (
 id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 certificate_alias VARCHAR2(255 CHAR) NOT NULL,
 subject_dn CLOB NOT NULL,
 issuer_dn CLOB NOT NULL,
 serial_number VARCHAR2(255 CHAR) NOT NULL,
 sha256_fingerprint VARCHAR2(128 CHAR) NOT NULL,
 valid_from TIMESTAMP NOT NULL,
 valid_until TIMESTAMP NOT NULL,
 source_host VARCHAR2(512 CHAR),
 source_port NUMBER(10),
 status VARCHAR2(64 CHAR) NOT NULL,
 certificate_der BLOB NOT NULL,
 created_at TIMESTAMP NOT NULL,
 created_by VARCHAR2(255 CHAR),
 CONSTRAINT pk_trusted_certificate PRIMARY KEY (id),
 CONSTRAINT uk_trusted_certificate_fp UNIQUE (sha256_fingerprint)
);
