CREATE TABLE user_partner_permission (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    partner_id NUMBER(19) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255),
    CONSTRAINT uk_user_partner_permission UNIQUE (user_id, partner_id),
    CONSTRAINT fk_upp_user FOREIGN KEY (user_id) REFERENCES app_user(id),
    CONSTRAINT fk_upp_partner FOREIGN KEY (partner_id) REFERENCES partner(id)
);
CREATE INDEX idx_upp_user ON user_partner_permission(user_id);
CREATE INDEX idx_upp_partner ON user_partner_permission(partner_id);

CREATE TABLE user_tax_permission_rule (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER(19) NOT NULL,
    rule_type VARCHAR2(10) NOT NULL,
    tax_number VARCHAR2(8),
    vat_code VARCHAR2(1),
    county_code VARCHAR2(2),
    sort_order INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    created_by VARCHAR2(255),
    CONSTRAINT fk_utpr_user FOREIGN KEY (user_id) REFERENCES app_user(id)
);
CREATE INDEX idx_utpr_user ON user_tax_permission_rule(user_id);
