-- Security and authorization schema for Oracle 19c+.
-- Database character set should be AL32UTF8.

create table app_user (
    id number(19) generated by default as identity primary key,
    username varchar2(255 char) not null,
    password_hash varchar2(255 char) not null,
    display_name varchar2(255 char),
    email varchar2(255 char),
    enabled number(1) default 1 not null,
    password_change_required number(1) default 0 not null,
    created_at timestamp default current_timestamp not null,
    created_by varchar2(255 char),
    updated_at timestamp,
    updated_by varchar2(255 char),
    constraint uk_app_user_username unique (username)
);

create table app_role (
    id number(19) generated by default as identity primary key,
    role_code varchar2(100 char) not null,
    role_name varchar2(255 char) not null,
    constraint uk_app_role_code unique (role_code)
);

create table app_user_role (
    user_id number(19) not null,
    role_id number(19) not null,
    primary key (user_id, role_id),
    constraint fk_app_user_role_user foreign key (user_id) references app_user(id),
    constraint fk_app_user_role_role foreign key (role_id) references app_role(id)
);

create index idx_app_user_enabled on app_user(enabled);
create index idx_app_user_role_role on app_user_role(role_id);
