create table xml_file_lock (
    id number generated by default as identity primary key,
    xml_file_id number not null,
    locked_by varchar2(255 char) not null,
    locked_at timestamp not null,
    lock_expires_at timestamp not null,
    lock_token varchar2(100 char) not null,
    status varchar2(50 char) not null,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp,
    constraint uk_xml_file_lock_file unique (xml_file_id),
    constraint uk_xml_file_lock_token unique (lock_token),
    constraint fk_xml_file_lock_file foreign key (xml_file_id) references xml_file(id)
);

create index idx_xml_file_lock_status on xml_file_lock(status);
create index idx_xml_file_lock_expires on xml_file_lock(lock_expires_at);

alter table xml_file_session add read_only number(1) default 0 not null;
alter table xml_file_session add lock_token varchar2(100 char);
alter table xml_file_session add close_reason varchar2(255 char);

create index idx_xml_file_session_user_active on xml_file_session(created_by, active);
