create table xml_file_revision (
    id number(19) generated by default as identity primary key,
    xml_file_id number(19) not null,
    revision_no number(10) not null,
    save_type varchar2(50 char) not null,
    target_file_path varchar2(2000 char),
    backup_file_path varchar2(2000 char),
    diff_summary varchar2(2000 char),
    change_count number(10) default 0 not null,
    xsd_validation_requested number(1) default 0 not null,
    xsd_validation_status varchar2(50 char),
    user_note varchar2(1000 char),
    created_at timestamp not null,
    created_by varchar2(255 char),
    constraint fk_xml_file_revision_file foreign key (xml_file_id) references xml_file(id)
);
create table xml_file_diff_entry (
    id number(19) generated by default as identity primary key,
    revision_id number(19) not null,
    xml_file_id number(19) not null,
    change_type varchar2(50 char) not null,
    xml_path varchar2(2000 char),
    old_value clob,
    new_value clob,
    display_label varchar2(1000 char),
    constraint fk_xml_file_diff_revision foreign key (revision_id) references xml_file_revision(id),
    constraint fk_xml_file_diff_file foreign key (xml_file_id) references xml_file(id)
);
create index idx_xml_file_revision_file on xml_file_revision(xml_file_id);
create index idx_xml_file_diff_revision on xml_file_diff_entry(revision_id);
create index idx_xml_file_diff_file on xml_file_diff_entry(xml_file_id);
